exclude: "^.github/.*/.*"

repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.3.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln

  - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        - id: check-toml
        - id: check-yaml
        - id: check-json
        - id: debug-statements
        - id: end-of-file-fixer
        - id: mixed-line-ending
          files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
        - id: trailing-whitespace
          files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-byte-order-marker
        - id: check-added-large-files
        - id: check-executables-have-shebangs

  - repo: https://github.com/asottile/setup-cfg-fmt
        rev: v2.5.0
        hooks:
        -   id: setup-cfg-fmt

  - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
      -   id: mypy

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
        args: [--py38-plus, --add-import, 'from __future__ import annotations']

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        args:
        - --max-line-length=80
        - --ignore-imports=yes
        - -d duplicate-code
