core:
  logging:
    path: "/opt/Automation/nfinity_flow_logs"

  services:
    - name: ssh
      instrument: os_ssh
      os_type: Linux
      sub_type: CentOS
      ip: 10.10.10.10
      users: root
      password: password
      port: 22

    - name: ac
      instrument: rasp_pi
      ip: 11.11.11.11
      user: root
      password: password
      port: 22
